apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  namespace: {{ .Values.namespace }}
data:
  postgresql-password: {{ template "postgres.database.encryptedPassword" . }}
  {{- if .Values.job.enabled }}
  {{- range $elm := (.Values.job.init.users) }}
    {{- $pass := default $elm.user $elm.password | b64enc | quote -}}
    {{- printf "%s: %s" $elm.user $pass | nindent 2}}
  {{- end }}
  {{- end }}