apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  namespace: {{ .Values.namespace }}
data:
  postgresql-password: {{ template "postgres.database.encryptedPassword" . }}