apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  namespace: {{ .Values.namespace }}
data:
  postgresql-password: {{ template "postgres.database.encryptedPassword" . }}
  {{- if .Values.job.enabled }}
  new-postgresql-password: {{ .Values.job.init.newUserPassword | b64enc | quote }}
  {{- end }}